### ISSUE TITLE
Unify environment variable naming

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-docker-compose#2]
We are currently "inventing" new variable names for env variables used by SODAR and SODAR Core. These should be unified where applicable, having multiple aliases for the same setting can get very confusing and frustrating to maintain.

E.g. `SODAR_ALLOW_LOCAL_USERS` should be renamed back to `PROJECTROLES_ALLOW_LOCAL_USERS` which is the actual variable used.

**Comment by holtgrewe** [comment]
More than agreed. We should also harmonize between SODAR, VarFish and Kiosc.

**Comment by mikkonie** [comment]
Also, suggestions for improving SODAR Core variable names are more than welcome! :)

**Comment by mikkonie** [comment]
Done. I prefixed SODAR-only env vars with `SODAR_*` for consistency and just in case there are dupes.
