### ISSUE TITLE
Some docker images in ghcr are not publicly readable

### ISSUE THREAD

**Issue by messersc** [bihealth/sodar-docker-compose#22]
I was not able to pull the davrods container because the permissions for the package are separate from the repo, although we can set inheritance, which is recommended.

```bash
Pulling davrods (ghcr.io/bihealth/davrods-docker:latest)...
ERROR: Head "https://ghcr.io/v2/bihealth/davrods-docker/manifests/latest": denied: denied
```

![image](https://user-images.githubusercontent.com/9218116/180787423-0392ec99-fea1-4e92-8fd4-bf00f2f828cf.png)

**Comment by mikkonie** [comment]
Good catch. You mention "some docker images", does this affect others than davrods-docker?

**Comment by messersc** [comment]
Tricky, because once you set up the token, the others will pull just fine. I think I checked irods-docker and that was set up correctly, which others do we pull?

Clemens

**Comment by mikkonie** [comment]
Can't find any related images with access not inherited, closing this issue. If some specific images exhibit problems, please open a separate ticket.
