### ISSUE TITLE
davrods with self-signed cert: 500 Internal Server Error

### ISSUE THREAD

**Issue by messersc** [bihealth/sodar-docker-compose#23]
Not sure what the problem is yet.

```
davrods_1                | [Mon Jul 25 14:30:38.485895 2022] [davrods:error] [pid 20] [client 172.18.0.3:58076] sslStart for PAM failed: -2103000 = SSL_HANDSHAKE_ERROR, referer: https://sodar.local/samplesheets/adff7193-d49e-454a-96e0-555cf38bb4ac
```

**Comment by mikkonie** [comment]
I will need to try to reproduce this error. Previously I've successfully set up Davrods with a self-signed cert. First guess would be some problem with the iRODS client configuration.

**Comment by mikkonie** [comment]
@messersc, can you provide the output written into the iRODS `rodsLog` file when this happens? That might provide some extra hints.

**Comment by messersc** [comment]
Hi Mikko, I think I solved the problem in the meantime, but I do not recall how.
I will post more info if I see it again.

Closing this for the moment.
Clemens
