### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by Hammarn** [bihealth/sodar-docker-compose#62]
Hi!
Do you have any experience with deploying SODAR through Kubernetes?
If that is the case, then do you have any Deployment files available?

**Comment by mikkonie** [comment]
Hi @Hammarn. At CUBI, we deploy SODAR using Ansible. At least so far, we haven't experimented with deploying SODAR on Kubernetes, so sadly I can't give much pointers there.

**Comment by Hammarn** [comment]
Thank you, just checking. Would just be nice to avoid duplicating work if possible, but then I know =)
